# Generated by Django 5.2.4 on 2025-07-31 15:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajones_inteligentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cajon',
            name='cajones_int_capacid_b7cbfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='objeto',
            name='cajones_int_codigo_3b833e_idx',
        ),
        migrations.RemoveField(
            model_name='cajon',
            name='capacidad_maxima',
        ),
        migrations.RemoveField(
            model_name='cajon',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='cajon',
            name='peso_maximo',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Peso máximo que puede contener el cajón en gramos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El peso máximo debe ser mayor que 0'), django.core.validators.MaxValueValidator(50000.0, message='El peso máximo no puede exceder 50kg')]),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso del objeto en gramos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El peso debe ser mayor que 0')]),
        ),
        migrations.AddIndex(
            model_name='cajon',
            index=models.Index(fields=['peso_maximo'], name='cajones_int_peso_ma_dee106_idx'),
        ),
        migrations.AddIndex(
            model_name='objeto',
            index=models.Index(fields=['peso'], name='cajones_int_peso_22ab55_idx'),
        ),
    ]
