# Generated by Django 5.2.4 on 2025-07-31 16:06

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajones_inteligentes', '0002_remove_codigo_ubicacion_change_capacidad_to_peso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cajon',
            name='cajones_int_peso_ma_dee106_idx',
        ),
        migrations.RemoveIndex(
            model_name='objeto',
            name='cajones_int_peso_22ab55_idx',
        ),
        migrations.RemoveField(
            model_name='cajon',
            name='peso_maximo',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='peso',
        ),
        migrations.AddField(
            model_name='cajon',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=10, help_text='Capacidad máxima de objetos que puede contener el cajón', validators=[django.core.validators.MinValueValidator(1, message='La capacidad debe ser al menos 1'), django.core.validators.MaxValueValidator(1000, message='La capacidad no puede exceder 1000')]),
        ),
        migrations.AddIndex(
            model_name='cajon',
            index=models.Index(fields=['capacidad_maxima'], name='cajones_int_capacid_b7cbfd_idx'),
        ),
    ]
