# Generated by Django 5.2.4 on 2025-07-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajones_inteligentes', '0003_remove_cajon_cajones_int_peso_ma_dee106_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='cajon',
            field=models.ForeignKey(blank=True, help_text='Cajón donde se almacena el objeto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='cajones_inteligentes.cajon'),
        ),
    ]
